---
steps:
- id: curio-generated-fetch-builder-image
  waitFor:
    - '-'
  name: curiostack/java-cloud-builder
  entrypoint: bash
  args:
    - -c
    - echo Fetched builder image.
- id: curio-generated-fetch-compressed-build-cache
  waitFor:
    - '-'
  name: curiostack/gsutil-lz4
  volumes:
  - name: gradle-wrapper
    path: /root/.gradle/wrapper
  - name: gradle-caches
    path: /root/.gradle/caches
  - name: curiostack
    path: /root/.gradle/curiostack
  dir: /root/.gradle
  entrypoint: ash
  args:
    - -c
    - gsutil cp gs://curioswitch-gradle-build-cache/cloudbuild-cache-compressed.tar.lz4 - | lz4 -dc - | tar -xp || echo Could not fetch compressed build cache...
- id: curio-generated-build-releases
  waitFor:
  - curio-generated-fetch-compressed-build-cache
  name: curiostack/java-cloud-builder
  volumes:
  - name: gradle-wrapper
    path: /root/.gradle/wrapper
  - name: gradle-caches
    path: /root/.gradle/caches
  - name: curiostack
    path: /root/.gradle/curiostack
  entrypoint: ./gradlew
  args:
  - releaseBuild
  - --stacktrace
  - --no-daemon
  env:
  - CI=true
  - TAG_NAME=$TAG_NAME
  - BRANCH_NAME=$BRANCH_NAME
timeout: 60m
