---
steps:
- id: curio-generated-deepen-git-repo
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/git
  args:
  - fetch
  - origin
  - master
  - --depth=10
  env:
  - CI=true
- id: curio-generated-fetch-uncompressed-build-cache
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/gsutil
  entrypoint: bash
  args:
  - -c
  - gsutil cp gs://curioswitch-gradle-build-cache/cloudbuild-cache-uncompressed.tar .gradle/cloudbuild-cache-uncompressed.tar && tar -xpPf .gradle/cloudbuild-cache-uncompressed.tar || echo Could not fetch uncompressed build cache...
  env:
  - CI=true
- id: curio-generated-fetch-compressed-build-cache
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/gsutil
  entrypoint: bash
  args:
  - -c
  - gsutil cp gs://curioswitch-gradle-build-cache/cloudbuild-cache-compressed.tar.gz .gradle/cloudbuild-cache-compressed.tar.gz && tar -xpPf .gradle/cloudbuild-cache-compressed.tar.gz || echo Could not fetch compressed build cache...
  env:
  - CI=true
- id: curio-generated-build-all
  waitFor:
  - curio-generated-deepen-git-repo
  - curio-generated-fetch-uncompressed-build-cache
  - curio-generated-fetch-compressed-build-cache
  name: openjdk:10-jdk-slim
  entrypoint: bash
  args:
  - -c
  - (test -e .gradle/cloudbuild-cache-uncompressed.tar && tar -xpPf .gradle/cloudbuild-cache-uncompressed.tar && tar -xpPf .gradle/cloudbuild-cache-compressed.tar.gz || echo No build cache yet.) && ./gradlew continuousBuild --stacktrace --no-daemon && tar -cpPf .gradle/cloudbuild-cache-uncompressed.tar /root/.gradle/wrapper /root/.gradle/caches /root/.gradle/curiostack && tar -cpPzf .gradle/cloudbuild-cache-compressed.tar.gz /usr/local/share/.cache /root/.gradle/go
  env:
  - CI=true
  - CI_MASTER=true
- id: curio-generated-push-uncompressed-build-cache
  waitFor:
  - curio-generated-build-all
  name: gcr.io/cloud-builders/gsutil
  args:
  - -o
  - GSUtil:parallel_composite_upload_threshold=150M
  - cp
  - .gradle/cloudbuild-cache-uncompressed.tar
  - gs://curioswitch-gradle-build-cache/cloudbuild-cache-uncompressed.tar
  env:
  - CI=true
- id: curio-generated-push-compressed-build-cache
  waitFor:
  - curio-generated-build-all
  name: gcr.io/cloud-builders/gsutil
  args:
  - -o
  - GSUtil:parallel_composite_upload_threshold=150M
  - cp
  - .gradle/cloudbuild-cache-compressed.tar.gz
  - gs://curioswitch-gradle-build-cache/cloudbuild-cache-compressed.tar.gz
  env:
  - CI=true
- id: curio-generated-build-curio-auth-server-image
  waitFor:
  - curio-generated-build-all
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e auth/server/build/docker && docker build --tag=asia.gcr.io/$PROJECT_ID/curio-auth-server --tag=asia.gcr.io/$PROJECT_ID/curio-auth-server:$REVISION_ID auth/server/build/docker || echo Skipping...
  env:
  - CI=true
- id: curio-generated-push-curio-auth-server-latest
  waitFor:
  - curio-generated-build-curio-auth-server-image
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e auth/server/build/docker && docker push asia.gcr.io/$PROJECT_ID/curio-auth-server || echo Skipping...
  env:
  - CI=true
- id: curio-generated-push-curio-auth-server-revision
  waitFor:
  - curio-generated-build-curio-auth-server-image
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e auth/server/build/docker && docker push asia.gcr.io/$PROJECT_ID/curio-auth-server:$REVISION_ID || echo Skipping...
  env:
  - CI=true
- id: curio-generated-deploy-curio-auth-server
  waitFor:
  - curio-generated-push-curio-auth-server-latest
  name: gcr.io/cloud-builders/kubectl
  entrypoint: /bin/bash
  args:
  - -c
  - 'test -e auth/server/build/docker && /builder/kubectl.bash --namespace=auth-dev patch deployment/curio-auth-server-alpha -p ''{"spec": {"template": {"metadata": {"labels": {"revision": "$REVISION_ID" }}}}}'' || echo Skipping...'
  env:
  - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
  - CLOUDSDK_CONTAINER_CLUSTER=curioswitch-cluster
- id: curio-generated-build-eggworld-server-image
  waitFor:
  - curio-generated-build-all
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e eggworld/server/build/docker && docker build --tag=asia.gcr.io/$PROJECT_ID/eggworld-server --tag=asia.gcr.io/$PROJECT_ID/eggworld-server:$REVISION_ID eggworld/server/build/docker || echo Skipping...
  env:
  - CI=true
- id: curio-generated-push-eggworld-server-latest
  waitFor:
  - curio-generated-build-eggworld-server-image
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e eggworld/server/build/docker && docker push asia.gcr.io/$PROJECT_ID/eggworld-server || echo Skipping...
  env:
  - CI=true
- id: curio-generated-push-eggworld-server-revision
  waitFor:
  - curio-generated-build-eggworld-server-image
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e eggworld/server/build/docker && docker push asia.gcr.io/$PROJECT_ID/eggworld-server:$REVISION_ID || echo Skipping...
  env:
  - CI=true
- id: curio-generated-deploy-eggworld-server
  waitFor:
  - curio-generated-push-eggworld-server-latest
  name: gcr.io/cloud-builders/kubectl
  entrypoint: /bin/bash
  args:
  - -c
  - 'test -e eggworld/server/build/docker && /builder/kubectl.bash --namespace=eggworld-server-dev patch deployment/eggworld-server-alpha -p ''{"spec": {"template": {"metadata": {"labels": {"revision": "$REVISION_ID" }}}}}'' || echo Skipping...'
  env:
  - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
  - CLOUDSDK_CONTAINER_CLUSTER=curioswitch-cluster
- id: curio-generated-build-curio-gateway-server-image
  waitFor:
  - curio-generated-build-all
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e gateway/server/build/docker && docker build --tag=asia.gcr.io/$PROJECT_ID/curio-gateway-server --tag=asia.gcr.io/$PROJECT_ID/curio-gateway-server:$REVISION_ID gateway/server/build/docker || echo Skipping...
  env:
  - CI=true
- id: curio-generated-push-curio-gateway-server-latest
  waitFor:
  - curio-generated-build-curio-gateway-server-image
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e gateway/server/build/docker && docker push asia.gcr.io/$PROJECT_ID/curio-gateway-server || echo Skipping...
  env:
  - CI=true
- id: curio-generated-push-curio-gateway-server-revision
  waitFor:
  - curio-generated-build-curio-gateway-server-image
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -c
  - test -e gateway/server/build/docker && docker push asia.gcr.io/$PROJECT_ID/curio-gateway-server:$REVISION_ID || echo Skipping...
  env:
  - CI=true
- id: curio-generated-deploy-curio-gateway-server
  waitFor:
  - curio-generated-push-curio-gateway-server-latest
  name: gcr.io/cloud-builders/kubectl
  entrypoint: /bin/bash
  args:
  - -c
  - 'test -e gateway/server/build/docker && /builder/kubectl.bash --namespace=curio-gateway-server-dev patch deployment/curio-gateway-server-alpha -p ''{"spec": {"template": {"metadata": {"labels": {"revision": "$REVISION_ID" }}}}}'' || echo Skipping...'
  env:
  - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
  - CLOUDSDK_CONTAINER_CLUSTER=curioswitch-cluster
