---
steps:
- id: curio-generated-deepen-git-repo
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/git
  args:
  - fetch
  - origin
  - master
  - --depth=10
  env:
  - CI=true
- id: curio-generated-fetch-builder-image
  waitFor:
  - '-'
  name: curiostack/java-cloud-builder
  entrypoint: bash
  args:
  - -c
  - echo Fetched builder image.
- id: curio-generated-fetch-compressed-build-cache
  waitFor:
  - '-'
  name: curiostack/gsutil-lz4
  volumes:
  - name: gradle-wrapper
    path: /root/.gradle/wrapper
  - name: gradle-caches
    path: /root/.gradle/caches
  dir: /root/.gradle
  entrypoint: ash
  args:
  - -c
  - gsutil cp gs://curioswitch-gradle-build-cache/cloudbuild-cache-compressed.tar.lz4 - | lz4 -dc - | tar -xp || echo Could not fetch compressed build cache...
- id: curio-generated-build-all
  waitFor:
  - curio-generated-deepen-git-repo
  - curio-generated-fetch-compressed-build-cache
  name: curiostack/java-cloud-builder
  volumes:
  - name: gradle-wrapper
    path: /root/.gradle/wrapper
  - name: gradle-caches
    path: /root/.gradle/caches
  entrypoint: ./gradlew
  args:
  - continuousBuild
  - --scan
  - --stacktrace
  - --no-daemon
  - -Pcuriostack.revisionId=$REVISION_ID
  env:
  - CI=true
  - CI_MASTER=true
- id: curio-generated-push-compressed-build-cache
  waitFor:
  - curio-generated-build-all
  name: curiostack/gsutil-lz4
  volumes:
  - name: gradle-wrapper
    path: /root/.gradle/wrapper
  - name: gradle-caches
    path: /root/.gradle/caches
  dir: /root/.gradle
  entrypoint: ash
  args:
  - -c
  - tar -cpf - wrapper caches curiostack/gcloud curiostack/miniconda2-build | lz4 -qc - | gsutil -o GSUtil:parallel_composite_upload_threshold=150M cp - gs://curioswitch-gradle-build-cache/cloudbuild-cache-compressed.tar.lz4
timeout: 60m
