apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: iap-backend-config
  namespace: |NAMESPACE|
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-oauth-creds
